import { idsToBits } from '../utils';

export enum Classes {
  Null,
  Warrior,
  Cleric,
  Paladin,
  Ranger,
  ShadowKnight,
  Druid,
  Monk,
  Bard,
  Rogue,
  Shaman,
  Necromancer,
  Wizard,
  Magician,
  Enchanter,
  Beastlord,
  Berserker,
  WarriorGM = 20,
  PaladinGM = 22,
  RangerGM = 23,
  BardGM = 27,
  MonkGM = 26,
  ShamanGM = 29,
  BeastlordGM = 34,
  RogueGM = 28,
  ShadowKnightGM = 24,
}

export const classIds: { [classNumber: number]: string } = {
  1: 'WAR',
  2: 'CLR',
  3: 'PAL',
  4: 'RNG',
  5: 'SHD',
  6: 'DRU',
  7: 'MNK',
  8: 'BRD',
  9: 'ROG',
  10: 'SHM',
  11: 'NEC',
  12: 'WIZ',
  13: 'MAG',
  14: 'ENC',
  15: 'BST',
  16: 'BER',
};
export const classBits = idsToBits(classIds, -1);

export const allClasses: { [classNumber: number]: string } = {
  1: 'Warrior',
  2: 'Cleric',
  3: 'Paladin',
  4: 'Ranger',
  5: 'Shadow Knight',
  6: 'Druid',
  7: 'Monk',
  8: 'Bard',
  9: 'Rogue',
  10: 'Shaman',
  11: 'Necromancer',
  12: 'Wizard',
  13: 'Magician',
  14: 'Enchanter',
  15: 'Beastlord',
  16: 'Berserker',
  20: 'Warrior Guildmaster',
  21: 'Cleric Guildmaster',
  22: 'Paladin Guildmaster',
  23: 'Ranger Guildmaster',
  24: 'Shadow Knight Guildmaster',
  25: 'Druid Guildmaster',
  26: 'Monk Guildmaster',
  27: 'Bard Guildmaster',
  28: 'Rogue Guildmaster',
  29: 'Shaman Guildmaster',
  30: 'Necromancer Guildmaster',
  31: 'Wizard Guildmaster',
  32: 'Magician Guildmaster',
  33: 'Enchanter Guildmaster',
  34: 'Beastlord Guildmaster',
  35: 'Berserker Guildmaster',
  40: 'Banker',
  41: 'Merchant',
};
