import { Item } from '../items/item.entity';

export enum ItemTypes {
  OneHandSlashing,
  TwoHandSlashing,
  OneHandPiercing,
  OneHandBlunt,
  TwoHandBlunt,
  Archery,
  Blank6,
  Throwing,
  Shield,
  Blank9,
  Armor,
  TradeskillItems,
  Lockpicking,
  Blank13,
  Food,
  Drink,
  Lightsource,
  CommonInventoryItem,
  BindWound,
  ThrownCastingItems,
  SpellsSongSheets,
  Potions,
  FletchedArrows,
  WindInstruments,
  StringedInstruments,
  BrassInstruments,
  PercussionInstruments,
  Ammo,
  Blank28,
  Jewelry,
  Blank30,
  ReadableNotesAndScrolls,
  ReadableBooks,
  Keys,
  OddItems,
  TwoHandPiercing,
  FishingPoles,
  FishingBait,
  AlcoholicBeverages,
  MoreKeys,
  Compasses,
  Poisons = 42,
  HandToHand = 45,
  Charms = 52,
  Dyes = 53,
  Augments = 54,
  AugmentSolvents = 55,
  AugmentDistillers = 56,
  FellowshipBannerMaterials = 58,
  CulturalArmorManuals = 60,
  NewCurrenciesLikeOrum = 63,
}

export const itemTypes: { [itemtype: number]: string } = {
  0: '1H Slashing',
  1: '2H Slashing',
  2: '1H Piercing',
  3: '1H Blunt',
  4: '2H Blunt',
  5: 'Archery',
  7: 'Throwing',
  8: 'Shield',
  10: 'Armor',
  11: 'Tradeskill Items',
  12: 'Lockpicking',
  14: 'Food',
  15: 'Drink',
  16: 'Light Source',
  17: 'Common Inventory Item',
  18: 'Bind Wound',
  19: 'Thrown Casting Items',
  20: 'Spells / Song Sheets',
  21: 'Potions',
  22: 'Fletched Arrows',
  23: 'Wind Instruments',
  24: 'Stringed Instruments',
  25: 'Brass Instruments',
  26: 'Percussion Instruments',
  27: 'Ammo',
  29: 'Jewelry',
  31: 'Readable Notes and Scrolls',
  32: 'Readable Books',
  33: 'Keys',
  34: 'Odd Items',
  35: '2H Piercing',
  36: 'Fishing Poles',
  37: 'Fishing Bait',
  38: 'Alcoholic Beverages',
  39: 'More Keys',
  40: 'Compasses',
  42: 'Poisons',
  45: 'Hand to Hand',
  52: 'Charms',
  53: 'Dyes',
  54: 'Augments',
  55: 'Augment Solvents',
  56: 'Augment Distillers',
  58: 'Fellowship Banner Materials',
  60: 'Cultural Armor Manuals',
  63: 'New Curencies like Orum',
};

export enum Skills {
  OneHandBlunt,
  OneHandSlashing,
  TwoHandBlunt,
  TwoHandSlashing,
  Abjuration,
  Alteration,
  ApplyPoison,
  Archery,
  Backstab,
  BindWound,
  Bash,
  Block,
  BrassInstruments,
  Channeling,
  Conjuration,
  Defense,
  Disarm,
  DisarmTraps,
  Divination,
  Dodge,
  DoubleAttack,
  DragonPunch,
  DualWield,
  EagleStrike,
  Evocation,
  FeignDeath,
  FlyingKick,
  Forage,
  HandToHand,
  Hide,
  Kick,
  Meditate,
  Mend,
  Offense,
  Parry,
  PickLock,
  OneHandPiercing,
  Riposte,
  RoundKick,
  SafeFall,
  SenseHeading,
  Sing,
  Sneak,
  SpecializeAbjuration,
  SpecializeAlteration,
  SpecializeConjuration,
  SpecializeDivination,
  SpecializeEvocation,
  PickPocket,
  StringedIntruments,
  Swimming,
  Throwing,
  TigerClaw,
  Tracking,
  WindInstruments,
  Fishing,
  MakePoison,
  Tinkering,
  Research,
  Alchemy,
  Baking,
  Tailoring,
  SenseTraps,
  Blacksmithing,
  Fletching,
  Brewing,
  AlcoholTolerance,
  Begging,
  JewelryMaking,
  Pottery,
  Percussion,
  Intimidation,
  Berserking,
  Taunt,
  Frenzy,
  RemoveTrap,
  TwoHandPiercing,
}

export const skills: { [id: number]: string } = {
  0: '1H Blunt',
  1: '1H Slashing',
  2: '2H Blunt',
  3: '2H Slashing',
  4: 'Abjuration',
  5: 'Alteration',
  6: 'Apply Poison',
  7: 'Archery',
  8: 'Backstab',
  9: 'Bind Wound',
  10: 'Bash',
  11: 'Block',
  12: 'Brass Instruments',
  13: 'Channeling',
  14: 'Conjuration',
  15: 'Defense',
  16: 'Disarm',
  17: 'Disarm Traps',
  18: 'Divination',
  19: 'Dodge',
  20: 'Double Attack',
  21: 'Dragon Punch',
  22: 'Dual Wield',
  23: 'Eagle Strike',
  24: 'Evocation',
  25: 'Feign Death',
  26: 'Flying Kick',
  27: 'Forage',
  28: 'Hand to Hand',
  29: 'Hide',
  30: 'Kick',
  31: 'Meditate',
  32: 'Mend',
  33: 'Offense',
  34: 'Parry',
  35: 'Pick Lock',
  36: '1H Piercing',
  37: 'Riposte',
  38: 'Round Kick',
  39: 'Safe Fall',
  40: 'Sense Heading',
  41: 'Singing',
  42: 'Sneak',
  43: 'Specialize Abjure',
  44: 'Specialize Alteration',
  45: 'Specialize Conjuration',
  46: 'Specialize Divination',
  47: 'Specialize Evocation',
  48: 'Pick Pockets',
  49: 'Stringed Instruments',
  50: 'Swimming',
  51: 'Throwing',
  52: 'Tiger Claw',
  53: 'Tracking',
  54: 'Wind Instruments',
  55: 'Fishing',
  56: 'Make Poison',
  57: 'Tinkering',
  58: 'Research',
  59: 'Alchemy',
  60: 'Baking',
  61: 'Tailoring',
  62: 'Sense Traps',
  63: 'Blacksmithing',
  64: 'Fletching',
  65: 'Brewing',
  66: 'Alcohol Tolerance',
  67: 'Begging',
  68: 'Jewelry Making',
  69: 'Pottery',
  70: 'Percussion Instruments',
  71: 'Intimidation',
  72: 'Berserking',
  73: 'Taunt',
  74: 'Frenzy',
  75: 'Remove Trap',
  76: '2H Piercing',
};

export function getSkillFromItemType(item: Item) {
  if (item.bagslots > 0) {
    return null;
  }
  const skillItemTypes = [0, 1, 2, 3, 4, 5, 7, 12, 23, 24, 25, 26, 35];
  if (skillItemTypes.includes(item.itemtype)) {
    return itemTypes[item.itemtype];
  }
  return null;
}

export const itemSizes: { [size: number]: string } = {
  0: 'TINY',
  1: 'SMALL',
  2: 'MEDIUM',
  3: 'LARGE',
  4: 'GIANT',
  5: 'GIGANTIC',
};

export const bardTypes: { [bardtype: number]: string } = {
  23: 'Wind Instruments',
  24: 'Stringed Instruments',
  25: 'Brass Instruments',
  26: 'Percussion Instruments',
  50: 'Singing',
  51: 'All',
};
